### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by kimiko-i** [kimiko-i/furima-31997#11]
挙動確認お願いいたします。

[フリマURL](https://furima-31997.herokuapp.com/)
Basic認証
　ID:admin    PW:2222
出品者
　アドレス: qweasd@qweasd    PW: qwe123
購入者
　アドレス: qqqq@qqqq   PW: qqq111
カード情報
　番号: 4242424242424242
　期限: 3/23
　セキュリティーコード: 123

**Comment by mutorisa** [comment]
ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

**[修正が必要な項目]**

- [ ] ログイン状態のユーザーが、URLを直接入力して売却済み商品の商品購入ページへ遷移しようとすると、トップページに遷移すること
**→現在は売却済み商品の購入ページに遷移してしまう状態です。トップページへ遷移するよう実装しましょう。**

- [ ] ログイン状態の出品者が、URLを直接入力して自身の出品した商品購入ページに遷移しようとすると、トップページに遷移すること
**→現在は出品者も商品購入ページに遷移する状態です。トップページへ遷移するよう実装しましょう。**

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by kimiko-i** [comment]
レビューありがとうございます。
修正いたしました。
よろしくお願いいたします。

**Comment by mutorisa** [comment]
再度ご提出ありがとうございます‼︎
動作の確認をしたところ、
`ログイン状態のユーザーが、URLを直接入力して売却済み商品の商品購入ページへ遷移しようとすると、トップページに遷移すること`
につていは修正の確認ができました✨

ただし、以下の項目については、前回と同じ状況で修正の確認ができませんでした。
今一度、本番環境で問題なく動作できるかご確認をお願いします！

- [ ] ログイン状態の出品者が、URLを直接入力して自身の出品した商品購入ページに遷移しようとすると、トップページに遷移すること
**→現在は出品者も商品購入ページに遷移する状態です。トップページへ遷移するよう実装しましょう。**

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by kimiko-i** [comment]
レビューありがとうございます。
再度挙動確認いたしましたが、ローカル環境でもherokuでもトップページに遷移するようになっていました。
テックコネクトで確認したかったのですが、現在対応できるメンターさんがいないということでしたので直接コメントいたしました。

**Comment by kimiko-i** [comment]
指摘いただいていた内容を正しく理解できていませんでした。
申し訳ございません。
再度ご確認よろしくお願いいたします。

**Comment by ayanasunakawa** [comment]
池田さん、再度のご提出ありがとうございます‼︎
前回指摘した点について修正が確認でき、問題なく正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
